### ISSUE TITLE
how to fix middleware issue 

### ISSUE THREAD

**Issue by loveunCG** [dellis23/django-wordpress-auth#12]
Hi Dear
I am using Django==2.0.5 with this library.
I have add config to my Django setting.py
but while importing 'wordpress_auth.middleware.WordPressAuthMiddleware', I have got issue
how to fix this 
thanks lots
>  mw_instance = middleware(handler)
TypeError: object() takes no parameters

**Comment by loveunCG** [comment]
> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001FEA8B8CAE8>
Traceback (most recent call last):
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\core\management\commands\runserver.py", line 140, in inner_run
    handler = self.get_handler(*args, **options)
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\contrib\staticfiles\management\commands\runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\core\management\commands\runserver.py", line 65, in get_handler
    return get_internal_wsgi_application()
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\core\servers\basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "H:\work_data\high-sq-technology\linkedin\jetbuzz\wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\core\wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\core\handlers\wsgi.py", line 140, in __init__
    self.load_middleware()
  File "H:\work_data\high-sq-technology\linkedin\venv\lib\site-packages\django\core\handlers\base.py", line 39, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

**Comment by Souvik1991** [comment]
Hey, @loveunCG I am stuck at the same issue what you had faced before.
Can you please help me with how you have fixed this issue?

Thank you in advance :)

**Comment by rafaelcanovas** [comment]
Hi there,

This exception has to do with the new middleware system introduced in Django 1.10.

There's a guide for upgrading to the new system here: https://docs.djangoproject.com/en/2.1/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

Hope I could help (despite without coding).

**Comment by dellis23** [comment]
Sorry for missing this.  I don't have time to maintain this project anymore but am happy to accept PRs for fixing issues that have arisen.
